### PR TITLE
Adding auth and routing navigation

### PR DESCRIPTION
**Pull request by kcords**

### CODE REVIEW

**Comment by kcords** [comment]
[2. Login: As a user I want to login to my account](https://trello.com/c/fZGiPC7K/19-2-login-as-a-user-i-want-to-login-to-my-account)

**Review by easleyjs — APPROVED** [review]
Looks good!

**Comment by kcords** [comment]
[Logout: As a user I want to log out of my account](https://trello.com/c/Y2uB9uJJ/32-logout-as-a-user-i-want-to-log-out-of-my-account)

**Comment by kcords** [comment]
[Navigate to prompt: As a user I want to view the prompt for an additional query](https://trello.com/c/u8wQbQ7C/33-navigate-to-prompt-as-a-user-i-want-to-view-the-prompt-for-an-additional-query)

**Pull request merged**
