### PR TITLE
Adds functionality to TaskModal for selected task

### PR DESCRIPTION
**Pull request by kcords**
- Updates route display based on authentication
- Adds NoteList
- Updates Welcome page message
- Adds NoteForm
- Adds NoteList
- Updates TaskList to display items
- Adds TaskModal
- Removes unnecessary file
- Updates version
- Separates api calls into a standalone file
- Corrects api bug
- Moves components into folder groups
- Moves TaskModal into Home
- Adds styling to completed tasks
- Updates task upon completion

### CODE REVIEW

**Comment by kcords** [comment]
[Add a note: As a user I want to add a note to one of my items](https://trello.com/c/utX64gWO/29-add-a-note-as-a-user-i-want-to-add-a-note-to-one-of-my-items)

**Comment by kcords** [comment]
[Complete task: As a user I want to mark tasks as complete](https://trello.com/c/dzX768JE/26-complete-task-as-a-user-i-want-to-mark-tasks-as-complete)

**Comment by kcords** [comment]
[Delete a note: As a user I want to delete a note from my task](https://trello.com/c/t6GQRIZB/30-delete-a-note-as-a-user-i-want-to-delete-a-note-from-my-task)

**Comment by kcords** [comment]
[Edit note: As a user I want to edit my note](https://trello.com/c/JbzuYS4O/24-edit-note-as-a-user-i-want-to-edit-my-note)

**Comment by kcords** [comment]
[Delete task: As a user I want to be able to delete a task](https://trello.com/c/QAI35y6j/31-delete-task-as-a-user-i-want-to-be-able-to-delete-a-task)

**Review by easleyjs — APPROVED** [review]
Cool, glad you got that issue figured out!

**Pull request merged**
